// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrsebshfyzvluinwvtcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyc2Vic2hmeXp2bHVpbnd2dGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTg2ODAsImV4cCI6MjA2NDg5NDY4MH0.m3vvS33DcUKnrrzT_I1s7TssY4Nx2JmeNveN0cSe-P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);